{{- if .Values.persistentVolume.enabled -}}
{{- if not .Values.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "burry.fullname" . }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- if .Values.persistentVolume.annotations }}
{{ toYaml .Values.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "burry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  {{- range .Values.persistentVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | quote }}
  {{- if .Values.persistentVolume.storageClass }}
    {{- if (eq "-" .Values.persistentVolume.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
    {{- end }}
  {{- end }}
  {{- if .Values.persistentVolume.selector }}
  selector:
{{ toYaml .Values.persistentVolume.selector | indent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
